services:
  # Main web service
  - type: web
    name: backgammon-news
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      limits:
        memory: 512M
      requests:
        memory: 256M
        cpu: 0.1

  # Background worker for news fetching - run as a separate service with its own memory allocation
  - type: worker
    name: backgammon-news-fetcher
    env: node
    buildCommand: npm install
    startCommand: node scripts/start-fetcher.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=256
    resources:
      limits:
        memory: 256M
      requests:
        memory: 128M
        cpu: 0.1
