services:
  # Main web service
  - type: web
    name: backgammon-news
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
      - key: NEXT_PUBLIC_MAX_NEWS_ITEMS
        value: "50"
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
    healthCheckPath: /api/health
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

  # Background worker for news fetching
  - type: worker
    name: backgammon-news-fetcher
    env: node
    buildCommand: npm ci
    startCommand: node scripts/start-fetcher.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=256
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
