services:
  # Main web service
  - type: web
    name: backgammon-news
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512 --gc-interval=100
      - key: NEXT_PUBLIC_MAX_NEWS_ITEMS
        value: "50"
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      limits:
        memory: 512M
      requests:
        memory: 256M
        cpu: 0.1
    healthCheckPath: /api/health
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 0.5

  # Background worker for news fetching - run as a separate service with its own memory allocation
  - type: worker
    name: backgammon-news-fetcher
    env: node
    buildCommand: npm install
    startCommand: node scripts/start-fetcher.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=256 --gc-interval=100
    resources:
      limits:
        memory: 256M
      requests:
        memory: 128M
        cpu: 0.1
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 0.5
